### ISSUE TITLE
Not respecting fire spread game rules

### ISSUE THREAD

**Issue by SonarBeserk** [ferreusveritas/Dynamic-Trees#100]
If a fire starts it appears to spread with no respect for any fire spread game rules. This occurs even running 0.7.8.

**Comment by ghost** [comment]
Can you elaborate on how it's violating the rules?

**Comment by SonarBeserk** [comment]
The typical function of the fire spread rule is to allow firespread when enabled and to prevent fire from spreading between blocks when disabled. Even when disabling the rule the dynamic trees allow fire to spread between their blocks.

**Comment by ghost** [comment]
Hmm.  I do derive a custom BlockVerboseFire from minecraft's vanilla BlockFire.  I needed to do this because of how the fire doesn't notify anything when it's about to destroy another block with fire.  I do however respect the "doFireTick" gamerule just like vanilla fire does.  So I'm not sure what could be going wrong.

**Comment by SonarBeserk** [comment]
It appears the rule being used was not the fire tick rule. That appears to have fixed the issue, thanks!
