### ISSUE TITLE
Root Block Glitch w/ Project Wish

### ISSUE THREAD

**Issue by WenXin20** [ferreusveritas/Dynamic-Trees#105]
Forge v14.23.4.2707-1.12.2
Dynamic Trees v0.7.8
[Project Wish](https://minecraft.curseforge.com/projects/project-wish?gameCategorySlug=mc-mods&projectID=285079) v0.0.7
When the stick block (ID is wish:stick@0) from Project Wish spawns next to the root block during world gen, this happens:
![2018-07-14_17 52 20](https://user-images.githubusercontent.com/12000593/42728994-6f10fda4-878f-11e8-97fe-7dba8fdc5ed4.png)
If this needs to be reported to the Project Wish mod instead, then I can do that.

**Comment by ghost** [comment]
This happens because of the mimic property of rooty dirt.  It will emulate the appearance of adjacent blocks whose material is Material.GRASS or Material.GROUND and then overlay a root texture over the model.   This was done to meet the impossible variety of modded dirt blocks out there.
The "wish:stick" is a block of which the material type is Material.GRASS.  This doesn't seem like the appropriate material for sticks to me but maybe there's a reason for it that unaware of.

**Comment by ghost** [comment]
Fixed in dev.  We'll only mimic blocks that are normal cubes.

**Comment by WenXin20** [comment]
OK, thanks
