### ISSUE TITLE
Compatiblity with no tree punching mods

### ISSUE THREAD

**Issue by Priderino** [ferreusveritas/Dynamic-Trees#110]
It would be great if Dynamic Trees was compatible with mods that disables getting wood with hands, requiring the player to get an axe first.

**Comment by ghost** [comment]
Can you give me an example of such a mod so I can see how their code handles it?

**Comment by Priderino** [comment]
These are the ones I know, sorry I don't have links, I'm on mobile.
Better With Mods
PrimalCore
No Tree Punching

**Comment by ghost** [comment]
This change should be all it needs.  After reading the source for the "No Tree Punching" mod I determined that it is keying off of the harvest tool for it's logic.  I never had a harvest tool set for the branches because vanilla never had it for it's logs.
PrimalCore has no available source therefor it's up to An-Sar to provide this functionality if it's needed.  As far as I understood PrimalCore was already supposed to be working with this ages ago.
