### ISSUE TITLE
Adding a dimension to the blacklist doesn't work

### ISSUE THREAD

**Issue by Peach774** [ferreusveritas/Dynamic-Trees#114]
It gives me a malformed config error when putting in -7. Ive tried placing it different places to check that I was wrong, but it doesnt work.

**Comment by Deshiba** [comment]
Since when do biomes work with negative numbers?

**Comment by Peach774** [comment]
Its not biomes its dimensions. Dimensions can have both positive and negative numbers. This the entry from the config file:
world {
    # Blacklist of dimension numbers for disabling Dynamic Tree worldgen [default: ]
    S:dimensionsBlacklist <
     >

**Comment by ghost** [comment]
I'll make sure I get this working before the next release.  Sorry for the inconvenience, it wasn't very well tested.

**Comment by ghost** [comment]
Works now.  An example syntax is as follows:

```
S:dimensionsBlacklist <
    -7
    -1
    7
>
```

Individual lines for each entry is **not** optional.  The syntax for forge config string lists are **very poorly** documented.

**Comment by Peach774** [comment]
I don't mean to bother you, but how soon should I expect an update? I can wait, I want to run my pack on a server, but I do not want to have some dynamic trees and some regular ones in the twilight forest if i can avoid it.

**Comment by ghost** [comment]
You can download the alpha version from curseforge.  That version has the bug fix.  However since it's alpha you might end up finding an unrelated bug or two.  That being said the alpha seems to run pretty ok.
I suggest testing with it anyway so if it doesn't work how you want you can report it to me and I'll get it fixed before the release version.

**Comment by Peach774** [comment]
So you currently have the default set to 7, which should probably be set to -7 since that is the twilight forest. If you leave it as 7, it could cause issues with RFTools dimensions and people might end up very confused.

**Comment by ghost** [comment]
Twilight Forest is 7.

https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/java/twilightforest/TFConfig.java#L34

**Comment by Peach774** [comment]
my bad

**Comment by Kiro-D-P1R4T3** [comment]
ok so the config file works with names now and it blows up when i enter int instead of string value.
what do i have to type so dynamic trees dont generate in the nether and the end ? (I specifically need that because dtbyg doesnt generate them properly)

Edit: found out the values were "overworld","the_nether" and "the_end" . . . . ofc

**Comment by Kiro-D-P1R4T3** [comment]
the black list doesn't work.
I enabled the vanilla gen trees, but added the overworld to the blacklist because its the only place i want dynamic trees, but it keeps them vanilla form some reason
