### ISSUE TITLE
[1.12.2-0.8.1i] Index Out Of Bounds Exception on Dedicated Server

### ISSUE THREAD

**Issue by kreezxil** [ferreusveritas/Dynamic-Trees#132]
I don't know what my players were doing but the follow crash was generated in the last 12 hours.

http://paste.ubuntu.com/p/cnzPv6vvYQ/

Let me know if it's really related to DT or not. Thanks.

**Comment by ghost** [comment]
Sorry it's taken so long to reply.  I see that this crash happened while it was under one of DTs routines but the code being run is simply setting a block to air at a given position.  Given that the PathWorldListener goes out of the "navigations" list bound immediately after a bounds check I would suspect there's another thread doing something naughty.  I'm nearly 100% sure that this is not caused by an error in Dynamic Trees.
