### ISSUE TITLE
[Suggestion] Config option for chance of tree

### ISSUE THREAD

**Issue by Andvee** [ferreusveritas/Dynamic-Trees#15]
Current worldgen option only allows world to start with all vanilla or all dynamic trees. I'd like to suggest a configurable option to set a chance that the mod replaces a vanilla tree with a dynamic tree.

**Comment by ghost** [comment]
If a vanilla tree is dropped into one of the poisson discs during worldgen it won't look right.  The way vanilla does worldgen tree placement is not compatible with DynamicTrees placement method.  I don't see this as being worth the effort especially since it will create a bunch of unforeseen issues that I will have to make little exceptions for.  There's also no point that I can see for this feature.
