### ISSUE TITLE
Question about API

### ISSUE THREAD

**Issue by WolfieWaffle** [ferreusveritas/Dynamic-Trees#17]
I'm trying to make a modded tree addon, but when I download the github for source and use the current jar on Curse I get different files. Certain files don't have source codes, some are missing etc. Should I compile a jar from GitHub, or can I just use the pure folder in my workspace?

**Comment by ghost** [comment]
The API is not stable at the moment.  Expect that it could change.  It shouldn't change so much that it's useless though so go ahead and use it if you want.  The reason that the jar on curse doesn't match what's on github is because what's on github is radically more developed and will be the future dynamic trees release that's coming soon.  I recommend you build the latest dynamic trees source from github and build for that.  I try to keep the "example trees" mod up to date with "dynamic trees" mod so look at that when things break.  The version that gets developed first is 1.12.2.  All others get backported whenever I decide to make a release.  I apologize for the inconvenience and please do keep in touch.  This is my first API and  you're the first person I'm aware of that's modding with my API.  So we're both in uncharted territory.

**Comment by WolfieWaffle** [comment]
I tried to build just from the cloned repo (local) and it gives me an error on :compileJava, do you know what that means?

**Comment by ghost** [comment]
I need more information.  
Do you have Java8 installed?
What version of Minecraft and forge are you using?
What are the steps you took to clone and build?
Are there any more details on the compile error?
You may not have done anything wrong but if it's my build files then I need to know because they work fine for me.

**Comment by WolfieWaffle** [comment]
I am running java 8, I dont know what forge and MC version I am using. I simply did git clone {url} and then gradlew build and it failed. I can run it with --stacktrace or --info or --debug etc. if you want.

**Comment by ghost** [comment]
git clone https://github.com/ferreusveritas/DynamicTrees.git -b 1.12.2
cd DynamicTrees
./gradlew setupdecompworkspace
./gradlew eclipse
./gradlew build

Try that.  That's for the 1.12.2 branch and I just went ahead and assumed you use eclipse.

**Comment by WolfieWaffle** [comment]
Hmm, I didn't set it up for eclipse the first time because I assumed I only needed the source but yeah I guess I can't build otherwise. I ran those though and everything completed but I see no jar file in build/libs, there is no libs folder inside build at all

**Comment by ghost** [comment]
Go to these links and download the latest 1.12.2 release for Quark and ComputerCraft(mod only depends on these for the build):
https://minecraft.curseforge.com/projects/quark/files
https://minecraft.curseforge.com/projects/computercraft/files

Make a "libs" directory in the same directory that you run gradlew and put those two mods in it.
Rebuild and it should make the jar you're after. It's most likely not the "right" way to do it but it'll work.

**Comment by ghost** [comment]
I'm assuming you got this working?  Haven't heard back from you.

**Comment by WolfieWaffle** [comment]
I got it working yeah, don't know what to do next and srry I tend to work on things erratically

**Comment by ghost** [comment]
Problem resolved
