### ISSUE TITLE
[minor bug] red sand to sand

### ISSUE THREAD

**Issue by HurtsAsHell** [ferreusveritas/Dynamic-Trees#188]
it's not a big bug but I think it's right to tell you.

_tile.cactusbranch.name_ at the end of the animation transforms the red sand into sand.

In any case, great beautiful mod

**Comment by Redd56** [comment]
can confirm

**Comment by Deshiba** [comment]
Cross refference to similar issues in the dtbop git:

https://github.com/the-realest-stu/DynamicTrees-BOP/issues/31

https://github.com/the-realest-stu/DynamicTrees-BOP/issues/25

https://github.com/the-realest-stu/DynamicTrees-BOP/issues/22

This might warrent a closer look at the way rooty soil is currently working? Might there be a more elegant way to handle the block replacing so it doesnt require a manual fix from case to case basis?

@ferreusveritas

**Comment by ghost** [comment]
I recently changed the rooty soil block to turn into the soil block used for world gen in that biome provided there's a sample of that soil available on one of its sides.  I have not yet done this for the rooty sand block since   I haven't yet decided if it's worth it.  On the one hand it could be used to farm different colored sand.  On the other hand the biome should have so much of that sand that it shouldn't matter if the player is doing this inefficient method to recolor sand.
