### ISSUE TITLE
Ice and Fire compatibility

### ISSUE THREAD

**Issue by NetherDragon55** [ferreusveritas/Dynamic-Trees#198]
When fire dragons from I/F set dynamic trees on fire they leave a bunch of little wood bits that look horrible. I think it happens because when they set trees on fire they also replace random wood blocks of the tree with ash blocks so the tree doesn’t competely burn becouse the fire can’t spread through these blocks. The explanation I tried to give might be worng, it's just a supposition.
![2019-01-12_14 52 32](https://user-images.githubusercontent.com/34894538/51074055-50448600-167a-11e9-9b32-b816082fc746.png)

**Comment by kierajreed** [comment]
This should be handled by Ice and Fire.

The only issue Dynamic Trees needs to fix is client/server desync with fire and ghost blocks.

**Comment by ghost** [comment]
Not so sure that Ice and Fire could actually fix this since it would require "burned" Dynamic Tree branches.  Ice and Fire might be able to detect the size of the branch and only replace it with ash if it's a certain radius.  Maybe.. Just a suggestion.  The jury is still out on the best way to fix this and how.

**Comment by ghost** [comment]
Would require work from Ice and Fire to accomplish this.
