### ISSUE TITLE
[0.6.5] client npe crash when using forge 1.12.2 b2577

### ISSUE THREAD

**Issue by kreezxil** [ferreusveritas/Dynamic-Trees#21]
client crash report: https://pastebin.com/6kdzqtXb

Note: your mod is the only one loaded.

**Comment by ghost** [comment]
Could you try using the 0.7.1d Alpha version on curseforge to see if that one does the same thing?

**Comment by kreezxil** [comment]
still crashes

https://pastebin.com/ghg5m2Yt

I'd check and see what Immersive Engineering did, they have patched but not yet released.

**Comment by GreyMamoN** [comment]
DynamicTrees-1.12.2-0.6.5
DynamicTrees-1.12.2-0.7.1e

Crash with Forge-1.12.2-14.23.1.2576 and higher
The latest working version of Forge-1.12.2-14.23.1.2575

**Comment by ghost** [comment]
Thanks for the info GreyMamoN. Hopefully when I fix this the changes are backwards compatible.

**Comment by ghost** [comment]
kreezxil, It looks like the problem isn't fixed in Immersive Engineering though the issue has been closed. It is still being recommended to roll back to a prior version of forge.  I think it's a forge bug since the change has broken mods that were working fine.  I'm sure something has been changed with model handling code judging by the forge changelog.  I don't have the 10+ hours it would take for me to bang my head against the wall trying to figure out what's wrong.

Edit:  Nevermind.  I think I fixed it.
