### ISSUE TITLE
Crash with various oddites

### ISSUE THREAD

**Issue by zEpiixz** [ferreusveritas/Dynamic-Trees#211]
Crash with various oddites

the root problem likely lies in line 149 of BlockTrunkShell.
The mod autor of VO tries to fix it but hes not sure if this could cause anyproblems with other mod in the future.

Crash:
https://paste.dimdev.org/mosupenena.mccrash

**Comment by Deshiba** [comment]
14.23.5.2808 120 mods loaded, 119 mods active

That's a hefty mod list right there :D Anyway, You mention the author of VO tires to fix it, is there a conversation somewhere? Because I don't see anything open on the mod author's issue tracker on Curse, and the repo on Github is empty.

The wiki states "Rats... will gnaw on... any sufficiently-vulnerable wooden blocks", so I think this happens when a rat tries to eat a dynamic tree. Or in this case a giant rat:
varodd:rat_giant (com.lying.variousoddities.entity.hostile.EntityRatGiant)

So I think that the issue is with VO in this instance. Probably something about the way the rat tries to break the block, it's something custom I reckon instead of simulating a player block break. 

(not a coder so can't be certain)

**Comment by zEpiixz** [comment]
Well if you see the "normal" amout of the most modpacks are 150-200 now so i think the mods i have are kinda lite besides them. While 40% of the mod are Quality of life mods (map,jei +addons, controlling , crafttweaker... etc) and libaries. But im not here to justify myself for the modpack.

You can see on the number 40 on his issue tracker there is mine:

https://minecraft.curseforge.com/projects/various-oddities/issues/40

**Comment by ghost** [comment]
Can't support this since the source code for Various Oddities is not available(not opensource).
