### ISSUE TITLE
Feature request: Stumps

### ISSUE THREAD

**Issue by Daeruin** [ferreusveritas/Dynamic-Trees#215]
I would like to request that when felling a large tree, it leaves a stump behind. It's one of my favorite features from Better With Mods and really adds to my immersion in the game. Seems like it would be a perfect fit for this mod. I would suggest that you still allow the player to break the bottom block of the tree, but after the tree falls, that block would be replaced with a short stump block. Stumps would be harder to break than regular wood, and perhaps the stumps could even rot over time and eventually become easier to remove. The rooty soil could have a similar decay cycle.

**Comment by ghost** [comment]
You can set the maxBranchRotRadius in the configs to prevent the uncut portions of a tree(stumps) from rotting.  That's about as far as I'll go.  Most people would consider stumps a nuisance.

**Comment by CodedtoonCactus** [comment]
I personally love the idea of having to leave Stumps behind, but in my opinion, instead of being harder to break, they should only be removed with a Shovel (by digging the block underneath) instead of having to wait for it to rot. This process is just like the game Don't Starve, where when you cut down a tree, it leaves behind a stump (that will simply stay there), which can be removed using a shovel. Simple as that.
