### ISSUE TITLE
Some generated trees are vanilla whilst others are as normal.

### ISSUE THREAD

**Issue by Emypony** [ferreusveritas/Dynamic-Trees#252]
Sorry for the title, I couldn't think of anything better.

I'm having some issues with Dynamic Trees and I believe Biomes O' Plenty. I do have the compatibility mod for it, so I keep wondering what the issue is? I tried removing one at a time and testing them and it still didn't work. It used to be perfect in the beginning but over time (and with a new world) something must've happened.

Unsure if trees are supposed to look like this:
![2019-04-26_02 07 05](https://user-images.githubusercontent.com/35893942/56775984-66fa8d00-67d2-11e9-90c0-cfe01d8b4e1f.png)
as you can see down below, some trees seem to be vanilla, some work correctly
![2019-04-26_02 07 16](https://user-images.githubusercontent.com/35893942/56775998-7c6fb700-67d2-11e9-8560-8a8c96782593.png)
others ehm...end up looking like this?
![2019-04-26_02 07 52](https://user-images.githubusercontent.com/35893942/56776005-885b7900-67d2-11e9-9f74-b0d446687e7f.png)
Brown Tree seems to have vanilla features, white one looks to be working:
![2019-04-26_02 10 30](https://user-images.githubusercontent.com/35893942/56776013-9ad5b280-67d2-11e9-9a34-fff3e1b5559a.png)
Also...something seems to have happened with the texture?
![2019-04-26_02 19 32](https://user-images.githubusercontent.com/35893942/56776036-b50f9080-67d2-11e9-8a67-27c712ab97db.png)

I hope I'm not being mistaken of anything I write here. I saw that planting saplings will make trees spawn vanilla like, so I'm not complaining about those. Pictures are of trees found, not planted. I really hope you can help me.

**Comment by Deshiba** [comment]
Well, did you try without a texture pack?

Other then that, what versions of BoP, DTBoP and DT are you running? Could you post your mod pack?

**Comment by Emypony** [comment]
Hey there! Thanks for the reply!
Honestly, after restarting the game, it went back to being alright, so if I encounter it again I'll make sure to try it without the texture pack. (I use Clarity+1.12 just for reference)
I'm running the latest 1.12.2 versions of each, but I will post them below from inside my game:
![2019-04-26_21 39 02](https://user-images.githubusercontent.com/35893942/56829287-00c24880-686c-11e9-98fa-fbcbb224f8df.png)
![2019-04-26_21 39 28](https://user-images.githubusercontent.com/35893942/56829289-015adf00-686c-11e9-8898-a4b986f093c9.png)
![2019-04-26_21 39 30](https://user-images.githubusercontent.com/35893942/56829292-028c0c00-686c-11e9-805c-26275d83d3d5.png)
I'm not using a mod pack, I just took what I liked and made sure they're all for 1.12.2 (Sorry, I'm not sure how to show a mod list better, so I hope you don't mind me posting a snip from my mods folder.) 
![my mods list](https://user-images.githubusercontent.com/35893942/56828932-1aaf5b80-686b-11e9-83de-50faf842a37f.PNG)

**Comment by Deshiba** [comment]
This might be due to open terrain generator. As far as I understand that mod loads custom trees and such that might mess with Dynamic trees loading in world. In the past there were issues that noted this as well:
#18 
https://github.com/ferreusveritas/DynamicTrees/issues/150#issuecomment-434756591

**Comment by kierajreed** [comment]
It's definitely another mod's trees. Try using only Dynamic Trees and add mods one by one to test which it is. (For BoP, add the DT addon too.)

**Comment by Evolution0** [comment]
Just dropping in to say that after installing Open Terrain Generator and creating a new world I also started getting vanilla trees, Dynamic Trees, as well as trees that are vanilla yet with Dynamic Trees branches.

OTG (Well Biome Bundle specifically) includes its own custom trees and it seems Dynamic Trees cannot replace them correctly, I suppose the only work around might be to remove the `tree(etc)` options from the `.bc` files of each biome. It seems simply deleting the Trees folder causes it to just use vanilla trees. I'll test it when I get a chance.

After some testing it seems you **_can_** simply remove the Trees folder but you also have to remove all the `tree(etc)` lines from the `.bc` files. This works because as it was explained to me when trees are placed as custom objects in `CustomObject()` if they are missing they don't get replaced with vanilla trees like with `Tree()`.

**Comment by ghost** [comment]
Open Terrain Generator includes generation for it's own trees which I cannot disable.
