### ISSUE TITLE
stackoverflow in 1.12.2-0.9.5

### ISSUE THREAD

**Issue by kreezxil** [ferreusveritas/Dynamic-Trees#262]
## What Happened
While exploring on my dedicated server world for my pack World of Dragons a player crashed the server multiple times. The crash reports say it's a stackoverflow error and after the really long stack trace that implicates DynamicTrees the block being ticked is minecraft:fire.

## Server Crash Reports
http://paste.ubuntu.com/p/hQ4ThZptf7/
http://paste.ubuntu.com/p/qYx3RtM4zn/
http://paste.ubuntu.com/p/MzJ88Kw8Jp/
http://paste.ubuntu.com/p/CC4gcBNwh2/
http://paste.ubuntu.com/p/bY87JjV7pB/

**Comment by kreezxil** [comment]
I've extracted following data from the crash reports:
Coordinate | Chunk | Region
(32002,79,-25680) | 2000,-1605 | 62,-51
(32004,81,-25680)  
(32003,82,-25680)  
(32002,81,-25678)  
(32003,80,-25678) 

So you can look at the chunk yourself. Looks like someone set off an explosion or an explosion event has taken place. There are ton of dynamic:falling_trees in the chunk.


[r.62.-51.zip](https://github.com/ferreusveritas/DynamicTrees/files/3197816/r.62.-51.zip)

**Comment by kreezxil** [comment]
got a screenshot. there is a natural lava flow and a dragon nearby that caused a whole section of forest to burn down. 

![image](https://user-images.githubusercontent.com/3880072/58023871-85ecf600-7ad6-11e9-91d8-eda4a6dbb38e.png)

**Comment by bigenergy** [comment]
+1 
i am getting the same problem
https://hastebin.com/yaderufoxe.coffeescript

**Comment by Ma77h3hac83r** [comment]
Same thing here. 2 players on the server try to join and we get the same error. Another 4 can join just fine.

https://pastebin.com/RDh7Bd3Z

**Comment by kreezxil** [comment]
happened again, are you absent @ferreusveritas?

https://pastebin.com/PPK7xeWS

**Comment by ghost** [comment]
In a manner of speaking, yes.  I'm more or less absent.  I haven't had any time to commit to MC modding.  If someone is willing to look over the source code, find a fix and submit a pull request then I'll look it over and merge it.  Otherwise we'll just have to wait until I get around to it when I have time.  I'm sorry.

Edit:  If it's any consolation I'm running a server at home that crashes with this problem when I start it up.  So I'm fully aware of it and interested in a fix myself.

**Comment by ghost** [comment]
iirc this has been fixed.  If not then I'll reopen it.
