### ISSUE TITLE
[Suggestion] Break entire branch when one block is broken by non-players too

### ISSUE THREAD

**Issue by RypoFalem** [ferreusveritas/Dynamic-Trees#28]
Right now breaking branch blocks with, for example a bore lens mana spreader, only breaks a single block.

I think it would be neat and more consistent if breaking branches by any method behaved like fire or player-broken branches: breaking the rest of the branch.

**Comment by ghost** [comment]
I'm no expert but shouldn't the bore lens mana spreader be using a fake player at least for block destruction and calling the proper functions for having a block destroyed by a player in the world?
That's how every mod block breaker, turtle and autonomous activator I've encountered is put together.

**Comment by ghost** [comment]
hey ah, i'm using tree chopper mod and if i try to break a dynamic tree with an axe, tree doesn't fall.

**Comment by ghost** [comment]
What do you mean "fall"?

**Comment by ghost** [comment]
uhm, sorry for my bad explanation. all tree blocks (with leaves and branches) setting into air block but theres no drop. BUT if i break the tree with my hand, it works fine. tree falls and there is drop. but if i use an axe, theres no drop like saplings or sticks or wood.

**Comment by ghost** [comment]
The Dynamic Trees mod already cuts down the whole tree at the base without any other mods installed.
The tree chopper mod is probably attempting to map out a tree for removal that doesn't exist because my mapper gets to it first and has already removed the tree like it's supposed to.  As for why there's no log drops I can't explain that.
I read that tree chopper mod will disable it's harvesting if you hold shift while you cut the tree down.  What happens if you hold shift and cut down a dynamic tree with an axe?
Also this is off topic for the original posted issue.

**Comment by ghost** [comment]
Botania does not use a fake player to break blocks.  My mod uses removedByPlayer(...) which is called while the branch network is still unchanged.   BreakBlock(...) happens once it's too late and nodes have been removed from the branch network.  The result of this is that pieces are removed from the network without analyzing the whole tree first.  That's just how it works.  Some mods use a fake player to resolved problems like this with other mods.  Those that don't can expect this to happen.  As far as tree chopper goes it should work fine but for some reason drops aren't spawning.  However this has little to do with this issue.
