### ISSUE TITLE
Support for Newer Versions

### ISSUE THREAD

**Issue by Krorenshima** [ferreusveritas/Dynamic-Trees#285]
This may have been asked before, and I looked through the issues to make sure it hasn't.
Though, will there be 1.14+ support? Or is that not going to be worked on?

**Comment by VirtualGaming1** [comment]
+1 already missing this when starting playing 1.14

**Comment by RhymeofRain** [comment]
Same. Getting back into Minecraft after years of being away... This was a necessity for me before, hope it continues to update

**Comment by kierajreed** [comment]
1.14 support is planned but might take a while to implement.

**Comment by akinnee** [comment]
What happens if I play without this mod? Will I have no trees anymore? I want to upgrade my world to 1.14.4 from 1.12.2 and sadly this mod can't come along yet.

**Comment by kierajreed** [comment]
You will corrupt your world because the blocks won't be able to be found. Sorry.

**Comment by ttamttamS** [comment]
I absolutely love your mod! It really is a must have whenever it's available. I'm not specifically requesting this, but I was wondering what your thoughts were on using fabric. These kinds of world changing, technically involved, mods with limited scope seem pretty popular on the platform, although I may be wrong as I am not a mod developer. Thank you so much for your hard work!

**Comment by kierajreed** [comment]
I have not previously considered using Fabric, but if its API is better suited, I might. Thanks for the suggestion!

**Comment by ghost** [comment]
1.14.4 is being worked on.

**Comment by ttamttamS** [comment]
Hello, I hope everything is going well.
Could I suggest reopening and pinning this issue again? It seems like a lot of people aren't seeing this thread and making update issues. Not only is seeing all these "omg update to 1.18 now!" issues annoying, but it makes finding the original issue difficult now that they are not being linked back to this thread when closed. It also helps people like me  check in every now and then if this issue is pinned or left open. Thanks for all your hard work!

**Comment by ghost** [comment]
Not reopening this because it's a pointless issue.  It'll be updated to a later version when it's done.  There's also no reason to keep the issue open on account of fabric.  We really have no intention of using fabric.
