### ISSUE TITLE
Permission to adapt Dynamic Trees into Vintage Story

### ISSUE THREAD

**Issue by copygirl** [ferreusveritas/Dynamic-Trees#302]
I was looking into contacting you through ways other than creating an issue, but I haven't found any alternate contact method. So I hope this is fine.

The concept of dynamically growing trees was always something I wanted to implement, or see implemented, in Minecraft. I'm now curious to have a go at doing so in the voxel game [Vintage Story](https://www.vintagestory.at/). I have already started creating the block types necessary, seen in my [GrowingTrees repository](https://github.com/copygirl/GrowingTrees).

Since amazing work has already been done in this mod, I figured I'd learn and adapt the existing Dynamic Trees code for use in this mod. I'm guessing essentially taking a substantial amount of code, even if it is significantly modified, isn't in line with the MIT license. In addition it would only be fair to ask. So would it be okay if I did this, released the resulting code under Unlicense, with a big thank you in the readme and credits? Would you like to be credited as a contributor? (I would be happy to do so!) How and who should I credit?

Thank you!

**Comment by ghost** [comment]
Vintage Story is looking pretty nice.  Thank you for asking for permission to use my code.  You have my permission to include whatever you need from my source code, modified or otherwise.  I would appreciate being credited for my work.  Please refer to me as Ferreusveritas (Tracy Owens).  One word of caution is that the Dynamic Trees mod contains Minecraft code that's been copied and altered to fit specific purposes in a few locations.  While this is fine for Minecraft mods it may not be appropriate for your project.
