### ISSUE TITLE
Silkworms Hate these leaves

### ISSUE THREAD

**Issue by ShadeTheCat** [ferreusveritas/Dynamic-Trees#322]
So i added this to my skyblock and replaced all trees with the trees of this mod.
i tried to put a silkworm on one of the leaves and, nothing he did not want the leaves.
ok first off Dynamic trees and Ex Nihilo Creatio are the mods

So the silk worms do not like the leaves on a dynamic tree i have no clue why as other modded trees it works fine just not dynamic

there is a workaround by creating a normal sapling and planting that but its just annoying as its just extra work.

**Comment by ghost** [comment]
Dynamic Trees leaves are not registered in the OreDictionary as "treeLeaves" which is the only change required.  Since DT leaves are self replicating and not exactly the leaves that mods expect I can't guarantee that other mods will play nice with it.  It was left out to make my life easier and players happier.

Edit: As an example.  If I had registered DT leaves in the OreDictionary and ExHihiloCreatio's silk worm functionality had attempted to use them(at the time you posted this issue) it would have been crashing the game entirely because it was accessing properties in the block that weren't there instead of first checking to see if those properties exist.
