### ISSUE TITLE
Put bigger limit for branches to grow

### ISSUE THREAD

**Issue by Simex242** [ferreusveritas/Dynamic-Trees#344]
Hello, im making a project and for my needs i sometimes need oak trees or dark oak trees, acacia trees or any other but because all those trees have limits, only tree type that doesn't have limit is the redwood tree from biomesoplenty, im making custom trees and when  i spawn them just half branches disconnect from the tree because it has the like limit, i wish to know how can i increase that limit or that you make bigger limit.
![2019-10-18_19 13 36](https://user-images.githubusercontent.com/43273393/67114098-6b30c180-f1db-11e9-86be-52cfe8400ba9.png)

**Comment by ghost** [comment]
I can appreciate what your trying to accomplish but the limits for each tree species was carefully chosen so it doesn't cause side issues.  I would prefer not to make changes that can alter performance and stability for other players.  Redwoods have a high custom limit because they have limited branching and are required to be tall.

Edit:
As a workaround since you are building this in creative mode anyway would be to build the larger trunk structure in vanilla wood and place dirt blocks strategically and build the sections of the tree with dynamic tree parts using the woodland staff like you are.  Then use the setblock command to replace the rootydirt block with air.  Then replace the air block with vanilla wood.  The size of the trees you can make using this method is virtually unlimited.
