### ISSUE TITLE
Dynamic Inconsistencies in Dooglamoo World Gen

### ISSUE THREAD

**Issue by UnioMentium** [ferreusveritas/Dynamic-Trees#374]
**Describe the bug**
When using Dooglamoo worlds, it appears that some of the trees do not take the Dynamic appearance. This is probably a clash with how the mod generates vanilla terrain, I have no clue.

**To Reproduce**
Generate new world under category of Dooglamoo _(not Sm, Wt or SmWt varieties)_ and check out the various trees.

**Screenshots**
![2019-12-02_20 20 55](https://user-images.githubusercontent.com/15188272/70014867-692f8180-1541-11ea-9623-8a37fa9f154a.png)

![2019-12-02_20 29 26](https://user-images.githubusercontent.com/15188272/70015275-7ac55900-1542-11ea-95fb-7c74c90646db.png)

![2019-12-02_20 31 51](https://user-images.githubusercontent.com/15188272/70015539-4f8f3980-1543-11ea-9706-b42dfa4c1acf.png)

**Additional context**
It seemed to appear the most in the Plains biome. First encounter (I didn't get pictures), was in a much snowier biome consisting of Spruce and Birch.

**Comment by ghost** [comment]
Dooglamoo does it's own world generation server side.  It may ignore the forge event cancellation I use to prevent vanilla from creating trees and thus you end up with both DT and Vanilla trees.  At any rate Dooglamoo Worlds is closed source and since I can't investigate their source to correct the situation it is therefore unsupported.  The onus to fix this is on the authors of Dooglamoo Worlds.
