### ISSUE TITLE
CCL has caught an exception whilst rendering a block

### ISSUE THREAD

**Issue by lebanni** [ferreusveritas/Dynamic-Trees#398]
Versions :
forge-1.12.2-14.23.5.2847-universal.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
DynamicTrees-1.12.2-0.9.7.jar

Jungle trees are not rendered properly :
![2020-01-28_23 13 01](https://user-images.githubusercontent.com/2799575/73311489-d5b7bb80-4226-11ea-9a9d-d8103360f2e1.png)

[latest.log](https://github.com/ferreusveritas/DynamicTrees/files/4125060/latest.log)

**Comment by ghost** [comment]
The sheer number of mods and launcher errors in this error log forces me to ask you to simplify your setup, find the mods that aren't playing nice together, and then submit a new issue with more information.  I simply don't have the time to wade through such a huge mess.  The problem seems to be an interaction with Architecture Craft though I can't be certain.
