### ISSUE TITLE
Crash with "Exception in Server Tick Loop"

### ISSUE THREAD

**Issue by NisheethP** [ferreusveritas/Dynamic-Trees#408]
**Describe the bug**
Randomly getting "java.lang.NullPointerException: Exception in server tick loop". Just a crash with no signs. Happens withing a few minutes of starting the game. Has happened immediately afterwards as well. Started happening after I had been in the world for some time already

**Crashes**
Using version 0.9.7
Not using the other addons

**Mods List**
Using forge 1.12.2-14.23.5.2838)
[crash-2020-03-07_12.11.28-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/4301460/crash-2020-03-07_12.11.28-server.txt)

**Comment by kierajreed** [comment]
Please use [pastebin](https://pastebin.com/) for error logs and stack traces.

**Comment by NisheethP** [comment]
https://pastebin.com/6vaQvYH7

**Comment by ghost** [comment]
This crash seems strange to me.  It just dies in a locus that normally functions without fail.

**Comment by NisheethP** [comment]
Could this be some interaction with some other mod? Could Forestry's tree breeding or tree farms be responsible? I think that was the last major thing I had done before this started.

**Comment by ghost** [comment]
Unfortunately, the problem isn't unique to Nisheeth's environment, I'm getting the same issue on my server too. 
Crash log: https://pastebin.com/Mf6ejS0t

It appeared soon after I added some mods to my custom pack so it seems to be some kind of mod interaction issue. It runs for a few days or so and then it crashes without warning. After the crash, the world has to be restored from backup, otherwise it will crash again right after loading.

The list of the mods I added is here: https://pastebin.com/CdaCRw93
Before the upgrade, DT ran perfectly fine.

If you need more info or test something specific, just let me know, I'll be happy to help.

**Comment by kierajreed** [comment]
Mod interaction is tricky. You might have to resolve it client side-- sorry.

**Comment by ghost** [comment]
Latest curseforge download should resolve this issue.
