### ISSUE TITLE
Doesn't work on server

### ISSUE THREAD

**Issue by 2zl** [ferreusveritas/Dynamic-Trees#420]
**Mod Version:**

1.12.2-0.9.6

**Forge Version:**

forge-1.12.2-14.23.5.2854

**Link to client log:**

attached
[latest.log](https://github.com/OreCruncher/DynamicSurroundings/files/4557768/latest.log)

**Description:**

The mod just doesn't work on my server but when I use it in single player it works fine i have no clue why this is the case. Sorry for not having enough info

**Comment by 2zl** [comment]
FYI I'm not using the dev version like the other guy

**Comment by kierajreed** [comment]
Please use [pastebin](https://pastebin.com/) for error logs and stack traces. Also, please provide a mod list.

**Comment by Bengon** [comment]
I'm also having the same issue. Singleplayer works perfectly fine, but when I try to start a server it begins loading all the things as per usual until it reaches a point where the server stops and the CMD window closes.
Server Crash Log:[https://pastebin.com/uwMATDTv](https://pastebin.com/uwMATDTv)

**Comment by ghost** [comment]
@Bengon Your issue is crashing due to the DynamicTreesExc add-on mod trying to call client side code on the server.  Please report the issue to them.

@2zl Your crashlog does not implicate DynamicTrees in any way.  You've also given no explanation as to why you think it's DynamicTrees causing the crash.
