### ISSUE TITLE
DynTree Worlgen Mod Compatibility

### ISSUE THREAD

**Issue by LukaPix** [ferreusveritas/Dynamic-Trees#423]
I have seen this behaviour in combination with multiple Dungeon mods now, 
the one i am using right now is Pillar: https://github.com/Vazkii/Pillar
but this isn't an issue only with them.
Mods cannot generate their Structures correctly with DynTrees installed often generating them on top of the trees like the leaves were solid blocks.
It may be the leaves or the trunk but all of the mods i had this occur with, do not have this problem with vanilla trees.

How to recreate:
Install DynTrees+Pillar
Create an Structure using StructureBlocks
Import to pillar using /pillar-copy
Crank spawn rates in /pillar folder to make it easier to find

Most if not all of the structures will generate on top of the trees in densly grown areas.
I had this issue occur with the mod recurrent complex as well, but there it is much harder to replicate.

It may be something about in which order worldgen works in forge/mc but i really don't know.
Is DynTrees doing things differently than vanilla?

**Comment by ghost** [comment]
Structure mods like this have a hard time dealing with Dynamic Trees because if they break the branch blocks they get messed up trees, if they just generate around them they get messed up structures.  It's a no-win situation regardless.  The trees in Dynamic Trees generate as an IWorldGenerator with a modGenerationWeight of 20.  But regardless of order this will still happen because of chunk edges.
