### ISSUE TITLE
Random Music Disk Bug

### ISSUE THREAD

**Issue by SMHerobrine** [ferreusveritas/Dynamic-Trees#432]
**Describe the bug**
If you take a music disk out of a jukebox then the disk keeps playing 
(Idk how your mod did it but VanillaFix said that Dynamic Trees and Better Foliage made this issue)

**To Reproduce**
1) Download my modpack: https://www.curseforge.com/minecraft/modpacks/the-sm-modpack
2) Make a new world (better if in creative)
3) Take a jukebox and a random music disk (+even modded disks have this issue)
4) But the disk in the jukebox and take it out, the music doesn't stop

**Rendering Glitches**
Are you using Optifine?
No Rendering Glitches but I still use Optifine

**Additional context**
Crash Log: https://justpaste.it/5cgu5

**Crashes**
- Are you running the latest version of Dynamic Trees? (Currently 0.9.6) - no 0.9.8 (the current in 0.9.8 btw)
- If you are using the DT Biome O' Plenty Add-on do you have the latest version? (Currently 1.4.1e) - yes
- If you are using the DT Thaumcraft Add-on do you have the latest version? (Currently 1.4.1e) - no
If the above mods are current then please submit a full crash log.  The crash log normally contains the names of mods and their versions.  Don't be that guy who submitted a crash report without first checking that the versions are current.

**Mods List**
If your crash log does not contain a list of mods or you have no crash log then please provide a full list of the mods you are using complete with mod versions.
What version of Forge are you running? - 1.12.2 - 14.23.5.2854

**Comment by ghost** [comment]
The function in question is 
```
	@Override
	public void playEvent(EntityPlayer player, int type, BlockPos blockPosIn, int data) {
		Minecraft.getMinecraft().renderGlobal.playEvent(player, type, blockPosIn, data);
	}
```

Which is simply a pass-thru for the IWorldEventListener interface in Dynamic Trees.  That's the reason why it shows up in the crash log.  But it's not Dynamic Trees that's causing the problem.  It's also likely not Better Foliage for exactly the same reason.

However I don't understand the Kotlin code that octarine-noise uses to know for sure.  I can say that this line: `Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method mods.betterfoliage.client.chunk.ChunkOverlayManager.func_184377_a, parameter soundIn`
does appear to throw an error in Better Foliage saying that there's a null where there shouldn't be one.  Might be worth putting in an issue over at Better Foliage to find out.
