### ISSUE TITLE
Query/Possible bug.

### ISSUE THREAD

**Issue by Moobien** [ferreusveritas/Dynamic-Trees#46]
I planted some spruce cones about a week ago (minecraft week) and out of 20 trees i got a total of 16 spruce wood. Most of the trees dropped nothing whatsoever. I tried a tinkers mattock, broad axe and hatchet. I am yet to test it with vanilla tools.

Am I doing something wrong or have I encountered a bug?

**Comment by Moobien** [comment]
Side note, when i did cut the trees down the snow that had settled on leaves/branches remained floating magically in the air.

**Comment by ghost** [comment]
Please test with vanilla axe and post the result here.  I'll look into the snow issue.

**Comment by ghost** [comment]
To get experimental results you can grow a single tree and copy it with the woodland staff.

**Comment by Moobien** [comment]
Iron axe did the same thing.

**Comment by ghost** [comment]
I just tested spruce with vanilla tools and it works fine.  The snow doesn't hang either.  There might be another mod that's not playing nice.  A fully grown spruce tree in the open(not restricted by neighboring trees) will typically yield about 4-6 logs.  A tall skinny spruce in a forest(close to other trees) can yield about 2-3 logs.

**Comment by Moobien** [comment]
this is my modlist. https://gist.github.com/Moobien/b3f75003022ad9024d5bb09e4dbf8768

**Comment by ghost** [comment]
I appreciate the information but it's not likely that I'm going to go through all of those mods looking for the issue.  If you want to lend me a hand and divide and conquer test..

1. Remove all mods except the dynamic trees mod.  Create a new world and test.(This tests if there's a mod interaction problem at all).  The new world makes sure you don't break your regular world.
2. Add half of the mods ("A*-N*" for instance). Test in aforementioned new world.
3. If the problem doesn't exist then the most recently added mods are safe, add half of the suspect mods not in use. Test again.
4. Otherwise if the problem does exists then it's in the most recently added mods, remove half of the most recently added mods currently in use.  Test again.
5. Repeat from step 3 until conflicting mod is discovered.

You have 153 mods so it should take fewer than 8 iterations to isolate the problem to the exact mod.

**Comment by Moobien** [comment]
will do it in the morning, getting late here. for all I know I have done something wrong.

**Comment by ghost** [comment]
Did you find anything?

**Comment by ghost** [comment]
Closing issue due to unproductivity.

**Comment by Moobien** [comment]
Sorry have been busy helping find bugs in EnderIO the last few days

**Comment by ghost** [comment]
According to your list you have the Tree Chopper mod installed. It's most likely why it's broken.
