### ISSUE TITLE
Potions could be simplified?

### ISSUE THREAD

**Issue by Tar1q22** [ferreusveritas/Dynamic-Trees#530]
I just thought that since the project scope of this mod is trees and just trees, the potions system implemented could be simplified very easily, as most people wouldn't be bothered to use blaze powder and nether warts to edit a tree in some way. I think that a lot of the effects of potions could just be given to bonemeal, as that's the role it has in Minecraft anyway. As for the others they are already implemented in Minecraft already. For example:
- Instead of the potion of burgeoning bonemeal could just be applied to the tree or seed itself
- The potion of fertility is kind of redundant as bonemeal can already be used and is much easier to get
- Maybe a spider eye could be used instead of depletion
- Potion of persistance has practically the same effect as potion of depletion, so just maybe get rid of it
- 4 seeds could be used instead of the potion of Gigas, just like vanilla
- Potion of transformation is kind of redundant, I don't see a situation where youw ould need to use it instead of just growing another tree
- If you do that then biochar base isn't really needed either

I know changing all of that is kind of a stretch so maybe you could just remove some, like the potion of transformation, potion of fertility and the potion of persistance since they're kind of redundant. Anyway just my thoughts on how to make the mod a bit more simple, regardless it's a great mod anyway.

**Comment by Harleyoc1** [comment]
I think you're misunderstanding the utility of a lot of these potions. For example, the burgeoning is greater than bonemeal as it persists for a while longer, providing more growth, the fertility is not redundant as bonemeal does very little to re-fertilise the tree, the potion of persistence also turns the leaves to their vanilla counterparts so that they stop growing dynamically too, and the potion of transformation is useful if you want, for example, an oak tree in an acacia tree's shape. 

I don't think placing four seeds like in vanilla really works for this mod. First of all, dynamic trees can grow up to be 3x3 blocks, not 2x2, and even if you did 9 seeds it would be problematic - would the tree just automatically start growing the a thick branch? That would look weird and is not true to how trees grow. 

The other huge problem with removing these potions now is that they would disappear for anyone who has actually made them. 

We're certainly open to discussion of changing the recipes but I think the rest of these points aren't really valid.

**Comment by Harleyoc1** [comment]
We've discussed a set of changes to the potion system as it stands. Here are the changes:

- **Potion of Persistence**: Remove, confusing.
- **Potion of Burgeoning**: Fill fertility to max and then accelerate growth until fertility is depleted.
- **Potion of Fertility**: Remove, use bonemeal instead.
- **Potion of depletion**: Keep, for intentionally making small trees.
- **Bonemeal**: Make it restore 2 fertility points, short growth acceleration. Each application increases the remaining duration of the growth acceleration by some % until it reaches a maximum duration.
- **Potion of Denuding**: New potion that removes all the bark and leaves from a tree.
- **Potion of Harvest**: New potion that causes rapid fruit production.
- **Other potions**: Unchanged.

If you or anyone else has other suggestions please do comment, though due to a lack of discussion here I'll close this issue for the time being.

**Comment by Tar1q22** [comment]
Those changes look good to me, by rapid fruit production does that mean higher drop chance for apples? The new potions seem useful.

**Comment by Harleyoc1** [comment]
The harvest potion is very much subject to change. We are also discussing combining its effects with the burgeoning potion. 

Rapid fruit production, as I've currently implemented it, speeds up the growth of any fruit attached to the tree and the appearance of new fruit.
