### ISSUE TITLE
[Suggestion] Partial replacement of vanilla trees

### ISSUE THREAD

**Issue by scottosx** [ferreusveritas/Dynamic-Trees#54]
Would it be possible to have a config that allows for a certain percentage or number per chunk replacement of vanilla trees rather than all? This would accomplish a couple of things:

First, a bit better performance on potato PCs but still a nice looking world gen.
Second, the ability to really see the forests spread as starting with a lesser number of dynamic trees would make it more obvious.

This mod is a breathtaking and beautiful addition to Minecraft. Amazing job!

**Comment by Deshiba** [comment]
Due to the difference of the generation that vanilla uses and that which this mod implements, I don't think that's possible. Hold for a reply from the author though.

What you can do on potato pc's is not enable replacing vanilla spawn trough config and then craft and plant the DynamicTree "saplings" manually.

**Comment by ghost** [comment]
I don't think this feature would be worth the time I would have to spend on it.  It will add complications to a system that is already bursting at the seams with complexity.  This means it would likely cause more bugs and unintended consequences.  Many people would be confused by the feature which just means one more loose tile for them to trip over that I have to hear about and help them troubleshoot.  Sorry about your poor potato.
