### ISSUE TITLE
[Suggestion] More config options

### ISSUE THREAD

**Issue by Forstride** [ferreusveritas/Dynamic-Trees#55]
While there are a good amount of config options already, I feel like there are a few key ones missing that would *really* help make the mod better:

 - Replace DT seed drops w/ vanilla saplings.  There's already an option to place DT saplings when using vanilla saplings, but that doesn't change what drops from trees.

- Disable leaf sinking/movement slowing.  This is personally the biggest annoyance with the mod for me, and an option to disable it would be very, very nice.

- In the future, if separate Cacao trees are added, a way to disable those and just have cocoa beans planted on Jungle trees would be nice.  I mentioned this on the CurseForge page, but I feel like the mod works best as a "tweak" to vanilla, rather than a mod that adds its own actual content, and I personally wouldn't want to see it change from that.  But, if it does, config options to disable that kind of stuff would be very much appreciated.

**Comment by Deshiba** [comment]
* Skipping the first point.
* The second point already got a no in #9 but hopefully will be reconsidered.
* The third point might not be as worrysome as you think. Cacao trees would most likely be implemented like apple trees and those are toggled by config too:
> enableAppleTrees = config.getBoolean("enableAppleTrees", "trees", true, "If enabled apple trees will be generated during worldgen and oak trees will not drop apples");

**Comment by ghost** [comment]
Hey Forstride.  Much respect for your beautiful BoP mod which I am very much enjoying.  Here's my responses respectively to the suggestions you dropped. Though I'm afraid you may not like what I have to say.

- I don't want to make trees drop saplings because it's nonsensical.  Trees don't drop saplings(especially voluntarily) and it boggles my mind that Mojang thought it was an appropriate game mechanic.  The seeds provide a nice separation between what is a dynamic tree and what is not.  I was asked some time ago to optionally make the vanilla saplings plant dynamic trees for people that wanted to force the server into being completely dynamic trees.  I agreed to add that feature since I saw the added value for map makers and servers but I see no practical purpose for the converse behavior.

- Running around on the tops of trees doesn't make any sense.  I added this mechanic to prevent players from avoiding the perils of a forest by walking over the top of it where hostile mobs can't spawn.  This makes the game more fun because you must brave the forest in your adventure.  This was also added to balance the game play since vanilla "forests" don't typically have the trees close enough together to allow a player to travel large spans without ever touching the ground(except maybe roofed forests).  Since my mod creates forests that are effectively a large blanket of leaves I thought that this was the best way to balance it.  I have considered adding a footwear enchantment called "leaf hopper" that would allow a player to run on the tree tops but I have been shy about doing so since I already stated that I wouldn't add enchantments to a tree mod due to project scope.

- If Cacao trees are added I will treat it the same way I did as apple trees.  There's an option that totally removes apple trees and makes oak trees drop apples like you would expect.  Also because of project scope this would be the final fruit tree addition to DT.  I have no intention of adding more content and I consider Cocoa products from a specific species to be a valid addition.  I was presented with a good argument for their addition and since I was on the fence about it I let the community decide with a vote.  But since this isn't a democracy it's ultimately up to me if I follow through with it.  I take the project scope seriously because I want the mod to actually be finished one day and be feature complete.

**Comment by Forstride** [comment]
The first suggestion was mainly to keep things closer to vanilla for my own personal tastes.  I already have stuff like the separate apple trees and podzol generation disabled, and while the seeds are more realistic, I'd personally like something more "familiar" I guess.  Although I suppose I could technically use a resource pack to accomplish this.

As for normal movement on trees, it's less about evading mobs (Which I've never really considered TBH.  I even have a long path going through a dense and dark forest that I spent a lot of time working on and lighting up with torches), and more about it being annoying if you need to jump up on a tree to get a different angle while building something, or just want a nice vantage point to look out across a forest, which is something I've commonly run into in the past.  It really doesn't impact the actual gameplay for me, so it just ends up being an annoyance if I end up going on top of a tree for whatever reason.

**Comment by ghost** [comment]
Your hard work has made my play experience so much better that I feel that I should return the favor and make my mod with fewer annoyances for you.  I'll add a config option to disable the impeded travel on leaves during the next release cycle.  I'll also add an event so other mods can easily create an enchantment for the same reason.

**Comment by ghost** [comment]
Added config option to disabled enhanced leaves movement in dev version.
