### ISSUE TITLE
Sphax BDCraft Rooted Grass Texture Bug 1.16.5

### ISSUE THREAD

**Issue by allethargic** [ferreusveritas/Dynamic-Trees#559]
**Describe the bug**
Grass Block under tree (Rooted Grass) have no texture (Pink/Black Squares) when using with Sphax BDCraft. Other blocks on which trees can grow are working as intended.

**To Reproduce**
Install Sphax BDCraft. Install Dynamic Trees. Go to nearest Tree.

**Screenshots**
![image](https://user-images.githubusercontent.com/68805541/120694477-edeeb900-c4b2-11eb-9342-44fc2190efd3.png)

**Rendering Glitches**
Optifine is present.

**Comment by Harleyoc1** [comment]
This is caused by a resource pack. Rooty blocks use a multipart model based off the normal block and the root overlay seen in the above image. The resource pack is most likely making a change to the grass block texture that makes it incompatible. 

If resource packs change things in this way it's up to the user or the resource pack creator to add support, there is nothing we can do about this to my knowledge.
