### ISSUE TITLE
[Suggestion] Balance axe damage

### ISSUE THREAD

**Issue by Forstride** [ferreusveritas/Dynamic-Trees#56]
Right now, axes seem to take the same amount of damage no matter how large the tree you're breaking is.  It's kind of unbalanced in survival when I only have to break a single block to destroy a giant tree, and my axe only receives a tiny, tiny sliver of damage.

A damage multiplier config option to go with this might also be convenient to have.

**Comment by ghost** [comment]
What if the damage was related to the thickness of the trunk/branch that was being cut?  Rather than the size of the tree being felled.  Let's say 1 damage per radial unit of the branch for instance.

At the moment I balance the experience with more time spent harvesting thicker branches/trunks than with vanilla logs.  It also takes significantly more time to grow a tree to get a similar vanilla yield. So the survival is balanced in other ways.

I do see your point though since an axe would practically last forever compared to other tools.

**Comment by Forstride** [comment]
Well it takes more time to break the individual block, but if you're just harvesting trees for wood, it's the *only* block you need to break, compared to vanilla where you have to cut down the entire tree block-by-block.

Obviously it's not realistic to go by the height/how many logs you get, since you'd only be making a single cut in real life, but it's the most vanilla-esque option.

**Comment by ghost** [comment]
Config options for axe damage added in dev version.
