### ISSUE TITLE
Breaking a tree branch/trunk emits water particles

### ISSUE THREAD

**Issue by Brun333rp** [ferreusveritas/Dynamic-Trees#575]
**Describe the bug**
When breaking a tree branch or trunk, it will emit water particles instead of wooden ones.

**To Reproduce**
Simply chop down a tree or a branch.

**Rendering Glitches**
"Are you using OptiFine (or any equivalent mods that mess with rendering)?"
Answer: **Yes**

**Additional context**
This affects all the dynamic trees, with no exceptions.

**Comment by democat3457** [comment]
Send a screenshot at least, or a mod list or debug.log

**Comment by Brun333rp** [comment]
tomorrow I will send a picture if I remember about this

**Comment by Harleyoc1** [comment]
Don't worry about it we are aware of this issue. It has been around for a long time and is caused by the tree having such a big bounding box, which means that if it's near water or lava it emits the water particles or is on fire. We are considering some workaround for this, but being a pretty ineffectual bug in terms of gameplay it's low priority.
