### ISSUE TITLE
Incompatible with Realistic Block Physics

### ISSUE THREAD

**Issue by SeriousTIEM** [ferreusveritas/Dynamic-Trees#577]
Describe the Issue:
Perhaps stating the obvious, but when using with the Block Physics mod, tree growth causes all the tree's leaves to fall. 

Steps to reproduce:
Run this mod with Realistic Block Physics by xBigEllx

**Comment by Harleyoc1** [comment]
From a comment on their CF page: 

`Sorry for the late reply. If you're still having problems, it's probably best to just leave the blocks from Dynamic Trees without a physics definition. If you're using 'ApplyDefaultBlocks', you can simply add "dynamictrees" to the 'ApplyDefaultBlocksBlacklist' in order to prevent Dynamic Trees blocks from receiving a default physics definition.`

By the way, if that blacklist supports block tags you should be able to apply the `dynamictrees:leaves` tag to fix this for DT and all add-ons that support our tags.
