### ISSUE TITLE
Custom Leaves Issue

### ISSUE THREAD

**Issue by GhostSrCs** [ferreusveritas/Dynamic-Trees#582]
Hello and thanks in advance for reading/replying this thread... I wanted to request if it is possible and doesn't mess too much with the mod, that you may remove the custom leaves behavior and make a "Lite" Mod Version that uses vanilla leaves, because is messing in a wierd way with two of my mods ("Physics mod" and "Walljump mod") In the manner of that I can't walljump this leaves because of the realistic leaves behavior your mod gives to the leaves and with the physics mod every time a block is destroyed particles of said block crumbles to the ground leading to mayor fps drops due to a lot of leaves particles falling arround me on the forest  ( I tried disabling all the leaves on the physics mod side but doesn't seem to work because the leaves on the moded trees are custom in some way) Is Ok if you won't do it but it couldn't hurt to ask xD Thanks in advance

**Comment by Harleyoc1** [comment]
Using vanilla leaves isn't an option due to the custom behaviour required for leaves growth (changing the vanilla leaves would cause more incompatibilities than it would fix, I expect). 

You can already turn on the `vanillaLeavesCollision` option in the server config (`/saves/[world]/serverconfig`) if you'd like, which should fix the wall jump. As for the Physics mod they have a configurable blacklist which you should add the DT leaves blocks to.
