### ISSUE TITLE
[1.16.5] Trees don't drop seeds

### ISSUE THREAD

**Issue by lebanni** [ferreusveritas/Dynamic-Trees#593]
Versions : 
forge-1.16.5-36.1.32.jar
DynamicTrees-1.16.5-0.10.0-Beta17.jar
DynamicTreesPlus-1.16.5-0.1.0-Beta9.jar
DynamicTreesTerraForged-1.16.5-1.0.0.jar

Modlist : https://gist.github.com/lebanni/f2789120cf54a9af88b1e2a56e559e58

Trees don't drop seeds by themselves. I tried untouched config file and with seedOnlyForest = false.
They do drop seed when cut.

**Comment by Harleyoc1** [comment]
Not a bug. This is related to Serene Seasons compatibility and is now configurable, please view #477 for more details.

**Comment by lebanni** [comment]
Seasonal integration is enabled and I went through all seasons, and still no seeds dropping.

**Comment by Harleyoc1** [comment]
By default this is an incredibly rare event (which is intentional). The seed drop rate has a default of `0.01`, and is multiplied by a seasonal drop factor which means since you're using serene seasons it will be even rarer some of the time. 

I know for a fact that this works as intended; I just verified by cranking the chance up to 1 to double check they are actually dropping.

**Comment by Harleyoc1** [comment]
The point of this feature is to have forests very slowly grow over time. Don't expect to see a seed drop from a tree, on the default chance you'll probably never see one drop at all yourself.

**Comment by lebanni** [comment]
Thank you for the clarification.
