### ISSUE TITLE
[Complains] Overal complains about mod

### ISSUE THREAD

**Issue by DevTimur** [ferreusveritas/Dynamic-Trees#60]
1) When you break leave block, it regrow REALLY fast. Most of the time it looks like just server lag.
(Add timer before leaves start regrow again)
2) When you break branch, many leaves from other branches and even other trees break aswell.
(Now sure how you can fix that, maybe make so no leaves break untill whole tree got chopped)
3) You can't place sapling on dirt from other mods, where you usually can grow normal trees.
(Sure, you need "Root" block for tree to grow, but how about you allow to place sprout, but it will now grow, just stand there, and turn into stick after some time, or dead bush)
4) If you tweak drop rate of tree, you will NEVER get more then 64 logs from single chop. You need to break branches one by one to get more than 64 logs from single tree.
5) Not every "fertilizer" can work on your tree
(Sure, it may be problem of other mod adding fertilizer, but maybe you can do something.)

**Comment by ghost** [comment]
1. You probably have your random tick speed turned up to greater than 3.
2. I'm working on a possible solution for that
3. You can place the saplings on modded dirt if there's a add-on to support it.  I can't possibly support every dirt type that modders have created.
4. I'll see if I can make it drop multiple stacks instead of maxing out at the stack size limit.  I didn't expect players to turn the cheat multiplier so high.
5. I don't see why this is necessary but I'll look into it.
