### ISSUE TITLE
Incompatible with Cave Biome API

### ISSUE THREAD

**Issue by vKILLZONEv** [ferreusveritas/Dynamic-Trees#612]
Trees do not generate when Caves and Cliffs Backport is installed.

Steps to reproduce the behavior:  Load a new world.

No other mods are loaded.

- Caves and Cliffs : 6.2
- Dynamic Trees: 0.10.0-Beta24
- Forge: forge-36.2.0
- OS: Windows 10

**Comment by TrashLambo** [comment]
Caves and cliffs backport requires bgcore to be installed. Running only those two mods alone do generate dynamic trees in new worlds, although there are numerous floating branches created as well. These branches do not break on their own, or when other branches are placed onto them through creative mode, and must be broken manually.

I would have submitted this as a seperate issue, although I'd expect it to be closed and reposted here, as it is relevant. My apologies if that is not the case.

- Dynamic Trees: 0.10.0-Beta24
- Bgcore: 1.16.5-3.1.2
- Forge: 1.65.5-forge-36.2.0
- OS: Windows 10

**Comment by BastardNeko** [comment]
I just installed caves and cliffs backport 7.0 and this instantly started happening upon generating a new world/chunks. Is there a fix for this?

**Comment by SillyGoblin** [comment]
If it helps with this issue I have been using dynamic trees version 1.16.5-0.10.0-beta15 without these issues other than the issues that come with that version. I have tinkered with the both the versions of caves and cliffs and dynamic trees, with the results being that anything past the stated version of dynamic trees will have this issue with most versions of caves and cliffs, but 1.16.5-0.10.0-beta15 worked without no other noticeable issues in almost any version of caves and cliffs. I say most cause I remember an older version of caves and cliffs that had an issue of not generating trees at all with dynamic trees installed, but I'm not sure if that's still downloadable at this point and that was fixed with the later updates on their end.
