### ISSUE TITLE
Had this bug when running as server 1.16.5

### ISSUE THREAD

**Issue by Mr-Syntax** [ferreusveritas/Dynamic-Trees#625]
[crash-2021-09-18_22.44.50-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/7190618/crash-2021-09-18_22.44.50-server.txt)

its in this pack 

https://www.curseforge.com/minecraft/modpacks/chosencraft

**Comment by Harleyoc1** [comment]
Your server has gotten so behind that it has crashed. This is due to your server's performance, it's not related to any specific mod and happens in vanilla too. You can change the `max-tick-time` option in `server.properties` to a higher value or to `-1` to disable crashing, but it will only result in very large lag spikes instead of crashing.
