### ISSUE TITLE
`Walking on leaves blocks is slow and sinking` - make an optional option

### ISSUE THREAD

**Issue by GameBurrow** [ferreusveritas/Dynamic-Trees#627]
**Feature request rules**
This mod adds feature `Walking on leaves blocks is slow and sinking` and this something that I would like to request that is a logic that you can turn off from config.

**Comment by Harleyoc1** [comment]
You already can by disabling `vanillaLeavesCollision` in the server config. 

For more info on where to find configs in 1.16: 

#### Configs in 1.16
All paths are given relative to the Minecraft directory unless otherwise stated. `[world]` is a placeholder for a world name.

**Client** `config/dynamictrees-client.toml`
**Common** `config/dynamictrees-common.toml`
**Server [Singleplayer]** `saves/[world]/serverconfig/dynamictrees-server.toml`
**Server [Dedicated]** `[world]/serverconfig/dynamictrees-server.toml relative to the server folder`

The server config file, like any Forge server config file, can be placed in the `defaultconfigs/` folder in order to be automatically copied over to the `serverconfig` folder of each newly created world.
