### ISSUE TITLE
Theme was closed without any help or marks

### ISSUE THREAD

**Issue by EgorZverev** [ferreusveritas/Dynamic-Trees#629]
I opened the topic “Bug on the server with generation” but moderator just closed topic referring to the fact that the topic has already been discussed

My previous message of topic: “I have a bug: when I wander around the world, I see that some of the trees are broken. Trees just haven't a trunk. This generation of trees continues with further travel around the world. I would really like to see this mod in my assembly, but because of this bug, I have to delete it. Server's Forge is v. 36.2.2. There is no such problem in a single player game.

Dynamic Trees - Beta24”

I want to add that I did not install the “caves and cliffs” modification.
And more: Trees break down in vanilla biomes too. In singleplayer all is well

**Comment by Harleyoc1** [comment]
I assumed it was caused by this because the issue sounded very similar and the only reports we've had for anything like that (trees generating without a trunk in particular) have been due to the Caves and Cliffs API mod. Apologies, I should have checked first really. I have reopened the original issue.
