### ISSUE TITLE
Dynamic Trees Plus fails to load correctly

### ISSUE THREAD

**Issue by Egitet** [ferreusveritas/Dynamic-Trees#636]
**Description**
So I have been using Dynamic Trees Plus for the longest time without any issues and then suddenly I keep getting this error: "Dynamic Trees Plus (dynamictreesplus) has failed to load correctly     java.lang.NoClassDefFoundError"

Not really sure how to replicate it. But, here is the crashlog: https://gist.github.com/Egitet/3f2042c0c5797f98a3ffc8a1e5fe6b89

**Versions**

- Dynamic Trees: DynamicTreesPlus-1.16.5-0.1.0-Beta10.jar
- Forge:  36.2.0
- Java: 1.8.0_291
- OS: Windows 10 Pro

**Comment by Harleyoc1** [comment]
You are using beta 6, despite what you have specified in the versions, and that is the issue. The versions you're using is shown on the crash report, and it's definitely beta 6. Make sure you're using beta 10. 

I think people have been having issues with CF launcher doing weird stuff with versions recently, so I'm guessing that's the problem here and for whatever reason it has downgraded DT+ to beta 6.
