### ISSUE TITLE
Not working with resource pack

### ISSUE THREAD

**Issue by McFireWolf** [ferreusveritas/Dynamic-Trees#643]
I'm using this mod in conjunction with the resource pack "Depixel 3D" which makes blocks like the enchanting table and leaves 3D. If I search leaves in JEI, the normal 6 come up, and if I place any leaves, they appear as they should, 3D and wavy since I use optifine. But the leaves that spawn on the trees show up as regular leaves from the normal Depixel texture pack and don't wave. Also, they show up as leaves from this mod, but no such leaves exist in JEI and if i middle-click, I just get the leaves from the pack that act as they should. Screenshots Below

![2021-11-24_19 06 01](https://user-images.githubusercontent.com/61443684/143365708-e280f60a-a2c6-435b-9521-0f4a0bd30516.png)
![2021-11-24_19 06 21](https://user-images.githubusercontent.com/61443684/143365724-5e45ccb5-91cf-46d6-9901-a9e6edf7cef5.png)
![2021-11-24_19 06 26](https://user-images.githubusercontent.com/61443684/143365727-1e9afeaa-cc3c-4ce5-8bf4-872717c04278.png)

The first one shows the difference between the two leaves, the others show that they show up as different leaves when targetted. I just wanna fix this.

**Comment by Harleyoc1** [comment]
There's nothing we can do about this. Dynamic Trees has its own leaves block, you need to ask the resource pack creator to include support or add the block state files yourself. 

Same with shaders, you need to add the leaves entries to the `block.properties` file in the shader pack. All DT leaves share the same names as their vanilla counterparts, but with `dynamictrees` as the namespace (for example `dynamictrees:oak_leaves`). 

FYI the reason the leaves work when they are placed normally is because our leaves are only used on a Dynamic Tree. They have no item and drop the vanilla counterpart when sheared.
