### ISSUE TITLE
[Question] How to build the mod from source

### ISSUE THREAD

**Issue by Jummit** [ferreusveritas/Dynamic-Trees#72]
I was wondering how I could try out the latest version of the mod by building it from source, but it did'nt get me far. I tried to run `gradlew` with the `--build` argument _I think it was that_. Many projects have a description on how to build the source code in the readme. But just posting how to do it here will help me too. Thanks in advance!

**Comment by ghost** [comment]
It's pretty much the same for 99% of the gradle projects out there.

**First**:
`gradlew sDecW`  <-- This sets up a decompiled MC workspace "sDecW" is shorthand for "setupDecompWorkspace"

**Special considerations**:
My project needs 2 libraries in order to build correctly.  Quark and ComputerCraft.
make a directory named "libs" in the project root and put the 2 jar files of those projects in it.
I'm using ComputerCraft-1.80pr1-build0.jar and Quark-r1.4-120.jar at the moment.  Both of these are available on curseforge.

**If you want to develop in eclipse then**:
`gradlew eclipse`  <-- This sets up a ready to import project file for eclipse IDE.

**Finally to build to a jar file**:
`gradlew build`  <-- This builds the jar and puts it in build/libs in the main project folder

If you're developing in linux you'll need to prepend "./" to the gradle command to run it from the current directory.  ie: `./gradlew build`
