### ISSUE TITLE
Mod loading error has occurred

### ISSUE THREAD

**Issue by Jealguru** [ferreusveritas/Dynamic-Trees#724]
**Description**
Dynamic Trees (dynamictrees) has failed to load correctly
		org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
**To Reproduce**
1: Launch minecraft
2: Past the initial mod setup
3: Mod crashes and refuses to elaborate further

**Screenshots**
![Captura](https://user-images.githubusercontent.com/74574092/189660248-6f768cbc-f400-4948-a310-947558b57e01.PNG)

**Rendering Glitches**
-OptiFine_1.16.5_HD_U_G8
-TerraForged-1.16.5-0.2.15
-chocolate-1.3.0-1.16.4 (chocolate fix)
-betterbiomeblend-1.16.4-1.2.9
-RoadRunner-mc1.16.5-1.4.1
-smoothboot-forge-1.16.4-1.2.2

**Additional context**
-Like 110 mods my bad sorry :c
-Found interesting things on crash log
   1: APP:architectury.mixins.json (Architectury Api )
   2: APP:abnormals_core.mixins.json (Blueprint mod)
**Crashes**
https://gist.github.com/Jealguru/6b82d9738693dce3ecf026e174daa594

**Mods List**
On crash log I guess

**Versions**
- Dynamic Trees: 1.16.5-0.10.0-Beta34
- Forge: 1.16.5-36.2.39
- Java: 1.8.0_51, Oracle Corporation
- OS: idk

**Comment by Jealguru** [comment]
Found the problem or something, apparently Cavebiomeapi-1.16.5-1.4.2 (https://www.curseforge.com/minecraft/mc-mods/cavebiomeapi/files) were the one causing the mod to not start
Strange since on last Dynamic Trees: 1.16.5-0.10.0-Beta33 they worked fine

**Comment by Enterprise12nx01** [comment]
Also having this issue

**Comment by Harleyoc1** [comment]
This is the actual error: `Exception message: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector cba$makeTrees(Lnet/minecraft/world/ISeedReader;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/world/biome/Biome; in cavebiomeapi.mixins.json:compat.DTTreeGeneratorMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap cavebiomeapi.refmap.json`

Cave Biomes API's using Mixin which is likely now outdated due to some change to that class or method. Please report this to them as it appears they will need to update it for beta 34.
