### ISSUE TITLE
1.19.2, custom server, getting recipes removed

### ISSUE THREAD

**Issue by vgrynch** [ferreusveritas/Dynamic-Trees#796]
I'm using Arclite 1.19.2 as a custom server to run both Forge mods and plugins. 
I'm using both DynamicTrees-1.19.2-1.1.0-BETA5 and DynamicTreesPlus-1.19.2-1.1.1

I'm getting weird logs:
```
Tried to load unrecognized recipe: dynamictrees:azalea_seed_to_minecraft_azalea removed now.
Tried to load unrecognized recipe: dynamictreesplus:red_mushroom_seed_to_minecraft_red_mushroom removed now.
Tried to load unrecognized recipe: dynamictrees:oak_seed_to_minecraft_oak_sapling removed now.
Tried to load unrecognized recipe: dynamictreesplus:minecraft_red_mushroom_to_red_mushroom_seed removed now.
Tried to load unrecognized recipe: dynamictrees:dark_oak_seed_to_minecraft_dark_oak_sapling removed now.
Tried to load unrecognized recipe: dynamictreesplus:minecraft_brown_mushroom_to_brown_mushroom_seed removed now.
Tried to load unrecognized recipe: dynamictrees:minecraft_crimson_fungus_to_crimson_seed removed now.
Tried to load unrecognized recipe: dynamictrees:minecraft_acacia_sapling_to_acacia_seed removed now.
Tried to load unrecognized recipe: dynamictrees:birch_seed_to_minecraft_birch_sapling removed now.
Tried to load unrecognized recipe: dynamictrees:azalea_seed_to_minecraft_flowering_azalea removed now.
Tried to load unrecognized recipe: apotheosis:potion_charm_enchanting removed now.
Tried to load unrecognized recipe: dynamictrees:minecraft_birch_sapling_to_birch_seed removed now.
Tried to load unrecognized recipe: dynamictrees:minecraft_dark_oak_sapling_to_dark_oak_seed removed now.
Tried to load unrecognized recipe: dynamictrees:minecraft_azalea_to_azalea_seed removed now.
...
```

There are no other messages like these for other Forge mods with custom recipes, and I have a large number of mods. In the game, I do not have appropriate recipes displayed or working (i.e., I cannot convert seeds to saplings, for example). Everything else works well but this.

Please, can you improve/fix the way how recipes are registered, so they are not blocked? Looks like something is wrong with their defining as all other mods work well.

**Comment by Runburner** [comment]
Hello, I am running a 1.18.2 modpack and getting this same issue. Our server console will spam the same exact things. The sapling conversion recipes are showing Empty Tag items in place of the saplings in JEI recipes and for example we can't craft the Nature's Compass, it won't accept any kind of sapling even vanilla, the recipe just shows empty tags in place of the rotating saplings it shows that it accepts. However, I tested removing the Dynamic Tree's series of mods (all compats and Dyn Tree+) and we could craft the natures compass again and it accept tree saplings. I did a bit of digging and this seems to be a tag issue since 1.18 updated how tags work. 

Forge Version: 4.2.10
Mod Version: Dynamic Trees-1.18.2-1.0.4

Involved Mods with recipe issues known at this time
-Natures Compass 1.18.2-1.9.7-Forge

![Minecraft recpie bug](https://github.com/DynamicTreesTeam/DynamicTrees/assets/13475764/8e750aee-8b1f-4461-bac4-159aa659483e)

**Comment by Runburner** [comment]
I did some more testing and ran the /forge tags query on minecraft:oak_sapling.
The game returned the following with Dyanmic Trees NOT installed. When it was installed, it stripped everything except the Sereneseasons tags.
![Minecraft tags bug](https://github.com/DynamicTreesTeam/DynamicTrees/assets/13475764/b23d06c9-4a38-4b69-874f-c994be578a74)
