### ISSUE TITLE
No sprinting on leaves

### ISSUE THREAD

**Issue by Deshiba** [ferreusveritas/Dynamic-Trees#9]
With the changes to leave functionality you can't traverse a roofed forest anymore. You get slowed down when moving, can't sprint and issues arise simply jumping up leaf blocks. It feels similar to going down ladders without the climbing and in every direction.

Preferably this effect would only kick in from a height you would take fall damage from. This would allow normal traversing of trees and the regular use of leaf blocks for things like scaffolding.

**Comment by ferreusveritas** [comment]
Use vanilla leaves for scaffolding.  You can still acquire them with shears.
Sprinting around on the tops of trees seems ridiculous to me.  The reason why this slow down feature was added was to encourage travel through a forest under it's canopy like a normal creature would. In vanilla Minecraft you can sprint and jump between trees and that eats hunger pretty quickly.  Since this mod can make the forest canopy so much thicker it needed this feature to balance the gameplay. 
The ability to tree climb and absorb fall damage was added to sweeten the deal.
I will not change this behavior.

**Comment by Deshiba** [comment]
There's no chance of this function becoming optional trough config?

**Comment by ferreusveritas** [comment]
It doesn't seem sensible to me to be sprinting around on the tops of trees.  You can't even run on soul sand..  why on earth would running on leaves in the air be a thing?  
You want quick passage over a roofed forest like in Vanilla but I don't allow that in this mod.  If you want to avoid the dangers of a forest be prepared to pay with decreased mobility.  This feature shouldn't be made optional.
