### ISSUE TITLE
Snow is not removed in snowy biomes

### ISSUE THREAD

**Issue by lebanni** [ferreusveritas/Dynamic-Trees#90]
When you cut dynamic trees in snowy biomes, snow stays in the air, unlike not dynamic trees.

https://imgur.com/a/kIKnSNI

**Comment by ghost** [comment]
Oh crap.  That's nasty.  I wonder how I never noticed that.

**Comment by ghost** [comment]
Was this in single player mode or was this on a server?

**Comment by lebanni** [comment]
It's multiplayer. For testing purpose, I play on a client connected to a server on the same LAN.

**Comment by ghost** [comment]
I'm unable to reproduce this no matter what I try.  Singleplayer/Multiplayer Creative/Survival or what have you.  Could it be possible there's some kind of other mod interaction?  Could you do a test with just dynamic trees mod installed?

**Comment by lebanni** [comment]
Maybe it's Serene Seasons, from which the snow come from.

**Comment by ghost** [comment]
Can you temporarily remove Serene Seasons and make a new world and test it?

**Comment by lebanni** [comment]
Even without Serene Season, issue still remains. Here in Ice Plains or Cold Taiga :

https://imgur.com/a/r7d2thn

I have 170+ mods, it would be difficult to find the one in conflicting.

**Comment by lebanni** [comment]
The issue occurs only in multiplayer mode.

**Comment by ghost** [comment]
After the snow is hanging in air can you log out and log back in to see if they disappear?

**Comment by lebanni** [comment]
The snow stays in the air after logging out and back. Same thing after a server restart. I have to break the blocks manually.

**Comment by ghost** [comment]
Here's what we know:
- It's a multiplayer only issue.
- I'm unable to reproduce the problem even with multiplayer
- It's likely an interaction with one of the 170 mods.
- The error is not a client problem since logging out and in doesn't make the blocks disappear
- The issue does not appear to be tool related and happens every time however a tree is broken

Typical method for determining which mod is causing the problem(divide and conquer):
1. Remove half of the mods. 
2. Test
3. If the problem persists remove half of the remaining(or recently re-added) mods.  Go to step 2.
4. If the problem disappears then the problem is in one of the removed mods.
5. Re-add half of the previously removed mods. Go to step 2.

Using this method one can determine the bad relationship with a max of 7-8 iterations instead of 170(one at a time). In this case it's a problem because the mods need to be removed from the server and client as well and that takes more work.  This is because it's a multiplayer only problem.

The best I can do at this point is to ask you to list the mods you are using.  Maybe something will stick out.

**Comment by lebanni** [comment]
Here's the list :
http://modlister.com/server/IndustrialScience

I may take some time to find out the problematic mod.

**Comment by ghost** [comment]
Unable to reproduce / Issue is not productive

**Comment by lebanni** [comment]
I should have thought earlier, it's [FastLeafDecay](https://minecraft.curseforge.com/projects/fast-leaf-decay). I forgot i used this one. I open an issue on his github pointing to this one.
