### ISSUE TITLE
Reporting issues (including with other mods)

### ISSUE THREAD

**Issue by MistereMoth** [ferreusveritas/Dynamic-Trees#942]
-I'm having a hard time getting bees to spawn, can they even spawn from planted trees or just naturally? (and yes i'm planting them next to flowers) also when i finally found one, it was floating, i wonder if eventually the team could make their nest part of the tree itself, so they would be actually attached to the tree, stay consistent with its growth and not remain in the air once the tree falls, breaking the nest as well and angering the bees.

-I'm unable to plant dynamic trees on the soil variations from immersive weathering, like permafrost and silt.

-this is from the dynamic trees + addon, but might aswell mention it here (they're being developed by the same team anyway): dynamic giant mushrooms aren't dropping the stems from the enhanced mushrooms mod

-(Neapolitan addon): banana trees aren't growing at all, no matter how many rains have passed. and yes i'm giving them the needed space

From 1.12.2 to 1.20.1 i noticed that trees are dropping seeds way less often, i'm investigating this one however, could be issue with another mod.

**Comment by supermassimo** [comment]
1 - Bees should spawn just like they do in vanilla, we use the same odds and probabilities and we even implemented the mechanic where trees grow with nests when near a flower. They also connect with the tree and drop when the tree is felled, already like you suggested. Not sure what could be causing all of this not to work, maybe you have a mod that changes the beehive block.
2 - That would require a treepack, there is already one that does just this on our discord server in the #community-treepacks channel.
3 - Idem to number 2, download the enhanced mushrooms treepack from the discord server.
4 - Neapolitan bananas have a lot of weird requirements to grow, dynamic trees just replicate those requirements from the original neapolitan mod, so make sure to follow those requirements. If you find the behavior differs and the regular banana plant grows while the dynamic one doesn't, please report that to us.
5 - I don't recall updating the drop rates since 1.12. Seed drops are affected by seasons. So make sure its not winter, or you don't have a season mod installed.

**Comment by MistereMoth** [comment]
> 1 - Bees should spawn just like they do in vanilla, we use the same odds and probabilities and we even implemented the mechanic where trees grow with nests when near a flower. They also connect with the tree and drop when the tree is felled, already like you suggested. Not sure what could be causing all of this not to work, maybe you have a mod that changes the beehive block. 2 - That would require a treepack, there is already one that does just this on our discord server in the #community-treepacks channel. 3 - Idem to number 2, download the enhanced mushrooms treepack from the discord server. 4 - Neapolitan bananas have a lot of weird requirements to grow, dynamic trees just replicate those requirements from the original neapolitan mod, so make sure to follow those requirements. If you find the behavior differs and the regular banana plant grows while the dynamic one doesn't, please report that to us. 5 - I don't recall updating the drop rates since 1.12. Seed drops are affected by seasons. So make sure its not winter, or you don't have a season mod installed.

1- The only i can think of is buzzier bees, but i don't think it changes the bee nest itself.

5- Yeah i remember happening in every season, each tree drops 0-2 seeds on average no matter how many leaves it has. Also yeah makes sense, i'm not using a season mod in my 1.12.2 modpack
