### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by lebanni** [ferreusveritas/Dynamic-Trees#959]
Minecraft Version: 1.20.1

**Describe the bug**
Server crash at start.

**To Reproduce**
It seems SereneSeasons compatibility is involved. Start a server with SereneSeasons v9.1.0.0.
I have 300+ mods installed, I didn't try removing all other mods.

**Crashes**
crash report :
https://gist.github.com/lebanni/f8e8224dfaa730c5dc71bb1a478e0525

debug log :
https://gist.github.com/lebanni/29783e385d6dbaf625e21d16c3405bf7

**Comment by pebblesthepupp** [comment]
Same bug, according to adubbz "The crash is due to dynamic trees relying on a class which doesn't exist in the backported version of the mod" so it'll likely take Dynamic Trees updating for Serene Seasons to work with it. I fixed it by just downgrading Serene Seasons down to 9.0.0.46, and GlitchCore down to 0.0.1.0

**Comment by Eurus001** [comment]
Same bug

Log: https://mclo.gs/tMAjdlS

**Comment by Scarlet-Fury** [comment]
Same crash but tested with JUST Dynamic Trees, Glitchcore and Serene Seasons. Happens on initializing a single player world too.

Seems that Dynamic Trees is looking for a class that defines the Serene Seasons Server Config, but no such class exists in the most recent backport of Serene Seasons

Here's the crash report:
[crash-2024-10-22_17.19.39-server.txt](https://github.com/user-attachments/files/17483110/crash-2024-10-22_17.19.39-server.txt)

**Comment by supermassimo** [comment]
fixed on 1.3.4
